name: pipeline aws 

on:
  push:
    branches:
      - main

    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # chequear el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # compilar el sitio (si aplica)
    - name: Build site
      run: |

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AKIA3C6FLWI2HMCGMEO5 }}
        aws-secret-access-key: ${{ secrets.cRdllo6uoZBYulmMiY0YjJBuyixREW/T1WQk5XEW }}
        aws-region: ${{ secrets.us-east-1 }}

    # subir archivos a el bucket
    - name: Sync files to S3
      run: |
        aws s3 sync ./path_to_your_files s3://${{ secrets.bucket-prueba-aws-ferrazuiz }} --delete

    # invalidar cache de cloudfront
    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.EB26P4ZMSJKZ }} --paths "/*"
      
